config/routes.rb
Baseballstats::Application.routes.draw do

  # Search Routes
  get "search/index"
  post "search/improved"
  post "search/slugging"
  post "search/fantasy_improved"
  post "search/triple_crown"
  
  resources :players do
    collection { post :import }
  end

  resources :batting_statistics do
    collection { post :import }  
  end

  resources :fantasy_points

  root :to => 'home#index'  
end

app/controllers/search_controller.rb
########################################################################
# The SearchController is responsible for handling search requests 
# against the batting statistics data and the fantasy point settings.
# Each search is implemented with a separate action. If we were to
# scale this controller, I would suggest using a design pattern based
# on the "Strategy" approach or something similar. The controller is
# not a RESTful resource controller.
########################################################################
class SearchController < ApplicationController

  ######################################################################
  # The index method presents a set of predefined search tabs based
  # on the current set of requirements.
  ######################################################################
  def index
    if params[:tab].present?
      case params[:tab]
      when 'tab1'
        @tab1 = 'class=active'
      when 'tab2'
        @tab2 = 'class=active'
      when 'tab3'
        @tab3 = 'class=active'
      when 'tab4'
        @tab4 = 'class=active'
      else
        @tab1 = 'class=active'
      end
    else
      @tab1 = 'class=active'
    end
  end

  ######################################################################
  # POST /improved
  #
  # The improved action calculates the most improved player for a given
  # time period and with a minium number of at bats. The parameters
  # that it expects are:
  #
  # * start_year
  # * end_year
  # * min_at_bats
  #
  # The end year must be greater than or equal to the start year and
  # the min_at_bats must be greater than 0.
  ######################################################################
  def improved
    @start_year = params[:start_year]
    @end_year = params[:end_year]
    @min_at_bats = params[:min_at_bats]
    
    if @end_year >= @start_year
      startstats = BattingStatistic.by_year(@start_year, @min_at_bats)
      endstats = BattingStatistic.by_year(@end_year, @min_at_bats)

      # Build hash of improvement scores - hash includes
      # player_id, improvement score. This is a brute force search,
      # we could implement something better later.
      improvements = {}
      last_stat = endstats.first
      
      endstats.each do |endstat|
        startstat = startstats.where(player_id: endstat.player_id).order_by([[:batting_average, :asc]]).first
        if startstat.present?
        
          # Check to see if we have multiple enteries for a player in 
          # the ending year. If we do use the best batting average
          if last_stat.player_id > endstat.player_id
            best_stat = last_stat             
          else
            best_stat = endstat
          end
          
          # Insert the improvment score into the hash using player_id as 
          # the key for the hash.
          improvements["#{endstat.player_id}"] = best_stat.batting_average - startstat.batting_average
        end
        
        last_stat = endstat
      end
      
      # Sort the improvement hash and label the winner
      improvements = improvements.sort_by {|k,v| v}.reverse

      if improvements.present?
        @winner = improvements[0]
        @player = Player.where(player_id: @winner[0]).first
      else
        @winner = @player = nil
      end
      
    else
      flash[:alert] = "End year must be greater than or equal to start year."
      redirect_to search_index_path(tab: 'tab1')
    end 
  end

  ######################################################################
  # The slugging action allows the user to submit a slugging percentage
  # search for a given year and team.
  ######################################################################
  def slugging
    @year = params[:year]
    @team = params[:team]
    
    if @year.present? && @team.present?
      @stats = BattingStatistic.team_slugging(@year, @team)
    else
      flash[:alert] = "You need to specify both a team and a year."
      redirect_to search_index_path(tab: 'tab2')
    end
  end

  ######################################################################
  # The fantasy_improved method will calculate the total fantasy points
  # for each player between two years. It will then collect the top
  # 5 results for display.
  ######################################################################
  def fantasy_improved
    @start_year = params[:start_year]
    @end_year = params[:end_year]
    @min_at_bats = params[:min_at_bats]

    if @end_year >= @start_year
      startstats = BattingStatistic.by_year(@start_year, @min_at_bats)
      start_points = fantasy_points(startstats)
      
      endstats = BattingStatistic.by_year(@end_year, @min_at_bats)
      end_points = fantasy_points(endstats)

      # Build hash of improvement scores - hash includes
      # player_id, improvement score. This is a brute force search,
      # we could implement something better later.
      @improvements = {}     
      
      end_points.each do |player, points|
        if start_points[player].present?
          @improvements[player] = points - start_points[player]
        end
      end

      # Sort the improvement hash and label the winner
      if @improvements.present?
        @improvements = @improvements.sort_by {|k,v| v}.reverse
        
        rlimit = @improvements.count < 5 ? (@improvements.count - 1) : 4 
        @results = @improvements[0..rlimit]
      else
        @results = nil
      end
      
    else
      flash[:alert] = "End year must be greater than or equal to start year."
      redirect_to search_index_path(tab: 'tab3')
    end
  end

  ######################################################################
  # The triple_crown method allows a search for a triple crown winner
  # for any given year. If it does not find a winner, the view will
  # display the closest results.
  ######################################################################
  def triple_crown
    @year = params[:year]
    stats = BattingStatistic.where(year: @year, :home_runs.gt => 0, 
      :runs_batted_in.gt => 0, :games_played.gt => 150)
    
    @ba_list = stats.where(batting_average: stats.max(:batting_average))
    @rbi_list = stats.where(runs_batted_in: stats.max(:runs_batted_in))
    @hr_list = stats.where(home_runs: stats.max(:home_runs))
    
    # Go throught home run list and check to see if any players are on
    # the other two lists.
    tc_winner = []
    @hr_list.each do |hrstat|
      if @ba_list.count > 1
        bastat = @ba_list.where(player_id: hrstat.player_id).first
      elsif @ba_list.count == 1
        bastat = @ba_list.first if @ba_list.first.player_id == hrstat.player_id
      else
        bastat = nil
      end
      
      if @rbi_list.count > 1
        rbistat = @rbi_list.where(player_id: hrstat.player_id).first
      elsif @rbi_list.count == 1
        rbistat = @ba_list.first if @rbi_list.first.player_id == hrstat.player_id
      else
        rbistat = nil
      end

      # Check to see if we have a winner
      if bastat.present? and rbistat.present?
        tc_winner << hrstat.player_id
      end
    end

    @player = tc_winner.present? ? Player.where(player_id: tc_winner[0]).first : nil
    @stats = stats.where(player_id: tc_winner[0]).first
    
  end
  
  
  ## Private Helper methods --------------------------------------------
  
  private
  
  ######################################################################
  # The fantasy_points method takes a list of batting statistics
  # and returns a hash with the player_id as the key and the fantasy
  # points as the value.
  ######################################################################
  def fantasy_points(stats)
    points = {}
    fan_points = FantasyPoint.first
    
    if fan_points.present?
      stats.each do |stat|
        hr_points = stat.home_runs * fan_points.home_run
        rbi_points = stat.runs_batted_in * fan_points.rbi
        base_points = stat.stolen_bases * fan_points.stolen_base
        stealing_points = stat.caught_stealing * fan_points.caught_stealing
        
        if points["#{stat.player_id}"].present?
          points["#{stat.player_id}"] = points["#{stat.player_id}"] + hr_points + rbi_points + base_points + stealing_points
        else
          points["#{stat.player_id}"] = hr_points + rbi_points + base_points + stealing_points        
        end
      end
    end
    
    return points
  end
   
end

app/helpers/search_helper.rb
module SearchHelper
  
  # Returns an array that can be used in the select tag helper
  def year_list
  
    years = []
    start_year = Date.today.year
    
    # Build year list
    200.times.each do |year|
      current_year = start_year - year
      years << ["#{current_year}", current_year]
    end
      
    return options_for_select(years)
  end
  
  # Returns an array of teams from the batting statistics data in
  # a format that can be used by the select tag helper
  def team_list
    teams = BattingStatistic.all.pluck(:team)
    teams = teams.uniq!
    
    team_array = []
    if teams.present?
      teams.each do | team |
        team_array << [team, team]
      end
    end
    team_array.sort!
    return options_for_select(team_array)
  end
  
  # Returns a string that holds the players first and last name or 
  # 'No player name found', if we cannot find the player record.
  def player_name(player_id)
    player = Player.where(player_id: player_id).first
    
    if player.present?
      str = "#{player.first_name} #{player.last_name}"
    else
      str = 'No player name found'
    end
    
    return str
  end
end

app/views/search/_fantasy_search.html.erb
<div class='row-fluid span10'>
  <h4>Most Improved Fantasy Player Search</h4>
  <p>
    You can use the form below to search for a most improved player based
    on the player's total fantasy points. The search allows you to specify the 
    starting year and ending year of the search. It also allows you to 
    specify the minimum number of at bats.
  </p>
  <p>
    Please note that the ending year must be greater than or equal to
    the starting year for the search. The minimum number of at bats must
    be greater than zero. The most improved calculation only examines 
    the fantasy points for the two years specified. It does not 
    look at a trend over multiple years. Also, if a player switched
    teams over any given year, all his points are accummulated.
  </p>
  <br/>
</div>

<div class='row-fluid span10'>
  <div class='form-horizontal'>
    <%= form_tag search_fantasy_improved_path do %>
    
      <!-- Starting year -->
      <div class='control-group'>
        <label class='control-label'>Starting Year</label>
        <div class='controls'>
          <%= select_tag(:start_year, year_list) %>
        </div>
      </div>

      <!-- Ending year -->
      <div class='control-group'>
        <label class='control-label'>Ending Year</label>
        <div class='controls'>
          <%= select_tag(:end_year, year_list) %>
        </div>
      </div>

      <!-- Minimum number of at bats -->
      <div class='control-group'>
        <label class='control-label'>Min. At Bats</label>
        <div class='controls'>
          <%= number_field_tag :min_at_bats, nil, min: 1 %>
        </div>
      </div>

      <div class='control-group'>
        <div class='controls'>
           <%= submit_tag "Search" %>
        </div>
      </div>
     
    <% end %>
  </div>  

</div>

app/views/search/_most_improved_search.html.erb
<div class='row-fluid span10'>
  <h4>Most Improved Player Search</h4>
  <p>
    You can use the form below to search for a most improved player based
    on the player's batting average. The search allows you to specify the 
    starting year and ending year of the search. It also allows you to 
    specify the minimum number of at bats.
  </p>
  <p>
    Please note that the ending year must be greater than or equal to
    the starting year for the search. The minimum number of at bats must
    be greater than zero. The most improved calculation only examines 
    the batting averages for the two years specified. It does not 
    look at a trend over multiple years.
  </p>
  <br/>
</div>

<div class='row-fluid span10'>
  <div class='form-horizontal'>
    <%= form_tag search_improved_path do %>
    
      <!-- Starting year -->
      <div class='control-group'>
        <label class='control-label'>Starting Year</label>
        <div class='controls'>
          <%= select_tag(:start_year, year_list) %>
        </div>
      </div>

      <!-- Ending year -->
      <div class='control-group'>
        <label class='control-label'>Ending Year</label>
        <div class='controls'>
          <%= select_tag(:end_year, year_list) %>
        </div>
      </div>

      <!-- Minimum number of at bats -->
      <div class='control-group'>
        <label class='control-label'>Min. At Bats</label>
        <div class='controls'>
          <%= number_field_tag :min_at_bats, nil, min: 1 %>
        </div>
      </div>

      <div class='control-group'>
        <div class='controls'>
           <%= submit_tag "Search" %>
        </div>
      </div>
     
    <% end %>
  </div>  

</div>

app/views/search/_search_tabs.html.erb
<!-- Search Navigation Tabs ---------------------------------------- -->
<div class="tabbable tabs-left">
  <ul class="nav nav-tabs">
    <li <%= @tab1 %>><a href="#tab1" data-toggle="tab">Most Improved</a></li>
    <li <%= @tab2 %>><a href="#tab2" data-toggle="tab">Slugging Percentage</a></li>
    <li <%= @tab3 %>><a href="#tab3" data-toggle="tab">Fantasy Players</a></li>
    <li <%= @tab4 %>><a href="#tab4" data-toggle="tab">Triple Crown Winner</a></li>
  </ul>
  <div class="tab-content">
    <div class="<%= if @tab1 then 'tab-pane active'  else 'tab-pane' end %>" id="tab1">
      <%= render 'most_improved_search' %>
    </div>
    <div class="<%= if @tab2 then 'tab-pane active'  else 'tab-pane' end %>" id="tab2">
      <%= render 'slugging_search' %>
    </div>
    <div class="<%= if @tab3 then 'tab-pane active'  else 'tab-pane' end %>" id="tab3">
      <%= render 'fantasy_search' %>
    </div> 
    <div class="<%= if @tab4 then 'tab-pane active'  else 'tab-pane' end %>" id="tab4">
      <%= render 'triple_crown_search' %>
    </div>     
  </div>
</div>

app/views/search/_slugging_search.html.erb
<div class='row-fluid span10'>
  <h4>Slugging Percentage Search</h4>
  <p>
    You can use the form below to search for the slugging percentage
    for all players on a given team for a given year.
  </p>
  <br/>
</div>

<div class='row-fluid span10'>
  <div class='form-horizontal'>
    <%= form_tag search_slugging_path do %>
    
      <!-- Search Year -->
      <div class='control-group'>
        <label class='control-label'>Year</label>
        <div class='controls'>
          <%= select_tag(:year, year_list) %>
        </div>
      </div>

      <!--Team selection -->
      <div class='control-group'>
        <label class='control-label'>Team</label>
        <div class='controls'>
          <%= select_tag(:team, team_list) %>
        </div>
      </div>

      <div class='control-group'>
        <div class='controls'>
           <%= submit_tag "Search" %>
        </div>
      </div>
     
    <% end %>
  </div>  

</div>

app/views/search/_triple_crown_search.html.erb
<div class='row-fluid span10'>
  <h4>Triple Crown Search</h4>
  <p>
    You can use the form below to search for the triple crown winner of
    a given year.
  </p>
  <br/>
</div>

<div class='row-fluid span10'>
  <div class='form-horizontal'>
    <%= form_tag search_triple_crown_path do %>
    
      <!-- Search Year -->
      <div class='control-group'>
        <label class='control-label'>Year</label>
        <div class='controls'>
          <%= select_tag(:year, year_list) %>
        </div>
      </div>

      <div class='control-group'>
        <div class='controls'>
           <%= submit_tag "Search" %>
        </div>
      </div>
     
    <% end %>
  </div>  

</div>

app/views/search/fantasy_improved.html.erb
<div class='page-header'>
  <h1>Most Improved Fantasy Point Player</h1>
  <p>
    The results for the most improved player search based on total 
    fantasy points are shown below for a search between
    <strong><%= @start_year %></strong> and 
    <strong><%= @end_year %></strong> with at least 
    <strong><%= @min_at_bats %></strong> at bats.
    The top 5 results are shown below.
  </p>
</div>

<% if @results.present? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Player ID</th>
        <th>Player Name</th>
        <th>Fantasy Points</th>
        
      </tr>
    </thead>
    <tbody>
      <% @results.each do |result| %>
        <tr>
          <td><%= result[0] %></td>
          <td><%= player_name(result[0]) %></td>
          <td><%= result[1] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <p>No results found for requested search criteria</p>
<% end %>

<div class='form-actions'>
  <%= link_to 'Return to Search', search_index_url, class: 'btn btn-primary' %>
</div>

app/views/search/improved.html.erb
<div class='page-header'>
  <h1>Most Improved Player</h1>
  <p>
    The results for the most improved player search are shown below 
    for a search between <strong><%= @start_year %></strong> and 
    <strong><%= @end_year %></strong> with at least 
    <strong><%= @min_at_bats %></strong> at bats. 
  </p>
</div>
 
<% if @player.present? %>
  <dl class="dl-horizontal">
    
    <dt><strong>First Name:</strong></dt>
    <dd><%= @player.first_name %></dd>
    
    <dt><strong>Last Name:</strong></dt>
    <dd><%= @player.last_name %></dd>
    
    <dt><strong>Improvment:</strong></dt>
    <dd><%= @winner[1].round(3) %></dd>       
  </dl>

<% else %>
  <p>No results found for requested search criteria</p>
<% end %>

<div class='form-actions'>
  <%= link_to 'Return to Search', search_index_url, class: 'btn btn-primary' %>
</div>

app/views/search/index.html.erb
<div class="page-header">
  <h1>Baseball Statistics Search</h1>

  <p>
    On this page you can see some sample search options represented by
    the tabs listed below along the left side of the screen.
  </p>
</div>

<%= render 'search_tabs' %>

app/views/search/slugging.html.erb
<div class='page-header'>
  <h1>Slugging Percentage Search</h1>
  <p>
    Below you will find the results of your search for the list of
    players and slugging percentages for the team <strong><%= @team %>
    </strong> during the year of <strong><%= @year %></strong>. The
    results are sorted from highest to lowest.
  </p>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Player ID</th>
      <th>Player Name</th>
      <th>Slugging Percentage</th>
      
    </tr>
  </thead>
  <tbody>
    <% @stats.each do |stat| %>
      <tr>
        <td><%= stat.player_id %></td>
        <td><%= player_name(stat.player_id) %></td>
        <td><%= number_to_percentage(stat.slugging_percent * 100, precision: 1) %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class='form-actions'>
  <%= link_to 'Return to Search', search_index_url, class: 'btn btn-primary' %>
</div>

app/views/search/triple_crown.html.erb
<<div class='page-header'>
  <h1>Triple Crown Search</h1>
  <p>
    Below you will find the results of your search for the triple crown
    winner for the year of <strong><%= @year %></strong>.
  </p>
</div>

<% if @player.present? %>
  <dl class="dl-horizontal">
    
    <dt><strong>First Name:</strong></dt>
    <dd><%= @player.first_name %></dd>
    
    <dt><strong>Last Name:</strong></dt>
    <dd><%= @player.last_name %></dd>
    
    <dt><strong>Batting Average:</strong></dt>
    <dd><%= @stats.batting_average.round(3) %></dd>  
 
    <dt><strong>RBI:</strong></dt>
    <dd><%= @stats.runs_batted_in %></dd>         
    
    <dt><strong>Home Runs:</strong></dt>
    <dd><%= @stats.home_runs %></dd>    
  </dl>

<% else %>
  <h5>No winner was found</h5>
  <p>
      The closest results are listed in the tables below:
  </p>
  <br/>
  
  <h5>Batting Average Leaders</h5>
  <table class="table table-striped triple_crown">
    <thead>
      <tr>
        <th>Player ID</th>
        <th>Player Name</th>
        <th>BA</th>
        
      </tr>
    </thead>
    <tbody>
      <% @ba_list.each do |bastat| %>
        <tr>
          <td><%= bastat.player_id %></td>
          <td><%= player_name(bastat.player_id) %></td>
          <td><%= bastat.batting_average.round(3) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>  

  <h5>RBI Leaders</h5>
  <table class="table table-striped triple_crown">
    <thead>
      <tr>
        <th>Player ID</th>
        <th>Player Name</th>
        <th>Runs Batted In</th>
        
      </tr>
    </thead>
    <tbody>
      <% @rbi_list.each do |rbistat| %>
        <tr>
          <td><%= rbistat.player_id %></td>
          <td><%= player_name(rbistat.player_id) %></td>
          <td><%= rbistat.runs_batted_in %></td>
        </tr>
      <% end %>
    </tbody>
  </table>  
  
  <h5>Home Run Leaders</h5>
  <table class="table table-striped triple_crown">
    <thead>
      <tr>
        <th>Player ID</th>
        <th>Player Name</th>
        <th>Home Runs</th>
        
      </tr>
    </thead>
    <tbody>
      <% @hr_list.each do |hrstat| %>
        <tr>
          <td><%= hrstat.player_id %></td>
          <td><%= player_name(hrstat.player_id) %></td>
          <td><%= hrstat.home_runs %></td>
        </tr>
      <% end %>
    </tbody>
  </table>    
<% end %>


<div class='form-actions'>
  <%= link_to 'Return to Search', search_index_url, class: 'btn btn-primary' %>
</div>