config/routes.rb
Baseballstats::Application.routes.draw do

  # Search Routes
  get "search/index"
  post "search/improved"
  post "search/slugging"
  post "search/fantasy_improved"
  post "search/triple_crown"
  
  resources :players do
    collection { post :import }
  end

  resources :batting_statistics do
    collection { post :import }  
  end

  resources :fantasy_points

  root :to => 'home#index'  
end

app/models/player.rb
########################################################################
# The Player model is designed to hold the player's name and birth year.
# for a single player for a given year. The player can either be
# imported or entered manually. The import format can be a CSV file with
# the following columns:
# 
# * playerID - unique id
# * birthYear
# * nameFirst
# * nameLast
#
# The entire set of player records will be index by player_id, which 
# should be unique.
########################################################################
class Player
  include Mongoid::Document
  include Mongoid::Timestamps
  
  # Add call to strip leading and trailing white spaces from all atributes
  strip_attributes  # See strip_attributes for more information
  
  ## CALLBACKS ---------------------------------------------------------
  
  ## ATTRIBUTES --------------------------------------------------------
    
  field :player_id, type: String
  field :birth_year, type: Integer, default: 0
  field :first_name, type: String
  field :last_name, type: String
  
  ## VALIDATIONS -------------------------------------------------------
  
  validates_presence_of :player_id
  validates_uniqueness_of :player_id
  validates_numericality_of :birth_year, allow_blank: true, greater_than_or_equal_to: 1700
  
  ## INDICES -----------------------------------------------------------
  
  index({player_id: 1}, {unique: true, name: "player_index" })
  
  ## PREDEFINED SCOPES -------------------------------------------------
  
  scope :by_player, ->(player){ where(player_id: player).order_by([[:player_id, :asc]]) }
  
  ## PUBLIC CLASS METHODS ----------------------------------------------
  
  ######################################################################
  # Returns number of skipped rows during import.
  ######################################################################
  def self.skipped 
    return @@skipped_rows
  end  
  
  ######################################################################
  # The import method handles importing a CSV file of player records.
  # It will overwrite the current set of players with the new ones
  # imported from the file.
  ######################################################################
  def self.import(file)
    Player.delete_all
    @@skipped_rows = 0
    
    CSV.foreach(file.path, headers: true) do |row|
      if row['playerID'].present?
        player = Player.new
        player.player_id = row['playerID']
        player.birth_year = row['birthYear']
        player.first_name = row['nameFirst']
        player.last_name = row['nameLast'] 
        if !player.save         
          logger.debug("[Player.import] Could not save imported record - error: #{player.errors.full_messages}")
        end
      else  
        @@skipped_rows += 1
      end
    end    
  end

  ## PRIVATE ITEMS -----------------------------------------------------
  
  private
    
  # Number of skipped rows during the import process
  @@skipped_rows = 0  
end

app/controllers/players_controller.rb
########################################################################
# The PlayersController is responsible for managing the
# interaction and updating of Player records. It has all the
# standard CRUD actions plus an action that supports uploading and
# replacing the system's player records from a CSV file.
########################################################################
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  before_action :set_players_menu_active
  
  ######################################################################
  # GET /players
  # GET /players.json
  #
  # Shows all players sorted by player ID and paginated.
  ######################################################################
  def index
    # Get page number from paginate plugin used in view
    page = params[:page].nil? ? 1 : params[:page]
  
    @players = Player.order_by([[ :player_id, :asc ]]).paginate(page: page, per_page: PAGE_COUNT)
  end

  ######################################################################
  # GET /players/1
  # GET /players/1.json
  # 
  # Shows an individual player record.
  ######################################################################
  def show
  end

  ######################################################################
  # GET /players/new
  #
  # Generates a new player record form.
  ######################################################################
  def new
    @player = Player.new
  end

  ######################################################################
  # GET /players/1/edit
  #
  # Generates an edit form for the requested player record.
  ######################################################################
  def edit
  end

  ######################################################################
  # POST /players
  # POST /players.json
  #
  # Creates a new player record.
  ######################################################################
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render action: 'show', status: :created, location: @player }
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  ######################################################################
  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  #
  # Updates an existing player record.
  ######################################################################
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  ######################################################################
  # DELETE /players/1
  # DELETE /players/1.json
  #
  # Destroys the requested player record.
  ######################################################################
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end

  ######################################################################
  # POST /players/import
  #
  # The import method allows uploading of a CSV file with batting 
  # statistics. It uses the Player model import class method
  # for uploading the batting statistics.
  ######################################################################
  def import
    Player.import(params[:file])
    message = "Players imported: #{Player.count} successful and #{Player.skipped} skipped."
    redirect_to players_url, notice: message 
  end

  ## PRIVATE INSTANCE METHODS ------------------------------------------

  private
    ####################################################################  
    # Use callbacks to share common setup or constraints between actions.
    ####################################################################
    def set_player
      @player = Player.find(params[:id])
    end

    ####################################################################
    # Callback to set the Batting Stats menu to active state
    ####################################################################
    def set_players_menu_active
      @players_menu_active = 'class=active'    
    end

    ####################################################################
    # Never trust parameters from the scary internet, only allow the white list through.
    ####################################################################
    def player_params
      params.require(:player).permit(:player_id, :birth_year, :first_name, :last_name)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for @player, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <label class='control-label' %>Player ID</label>
    <div class="controls">
      <%= f.text_field :player_id, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <label class='control-label' %>First Name</label>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <label class='control-label' %>Last Name</label>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <label class='control-label' %>Birth Year</label>
    <div class="controls">
      <%= f.text_field :birth_year, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                players_path, :class => 'btn' %>
  </div>
<% end %>

app/views/players/edit.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1>Edit Baseball Player Record</h1>
</div>
<%= render :partial => 'form' %>

app/views/players/index.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1>Baseball Players</h1>
  
  <div class="row-fluid">
    <div class="span8">
      <p>
        The list of baseball players currently loaded in the system are
        shown in the table below. There are currently <strong>
        <%= Player.count %></strong> player records loaded into the
        system.
      </p>
      <p>
        You can upload a new set of players into the system using the
        upload form below. <em>Please be aware that uploading a new
        set of players will replace the current set.</em>  All rows
        missing a <em>playerID</em> will be ignored. The file 
        format is expected to be in CSV format. The expected columns 
        and their order are shown to the right.
      </p>
      <br/>
      
      <!-- Upload form --------------------------------------------- -->
      <div class='pull-left'>
        <%= form_tag import_players_path, multipart: true do %>
          <%= file_field_tag :file %>
          <%= submit_tag "Import" %>
        <% end %>
      </div>  
    </div>
    
    <div class="well span3">
      <ol>
        <li>playerID</li>
        <li>birthYear</li>
        <li>nameFirst</li>
        <li>nameLast</li>
      </ul>
    </div>
  </div>
  
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:player_id) %></th>
      <th><%= model_class.human_attribute_name(:birth_year) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.player_id, player_path(player) %></td>
        <td><%= player.birth_year %></td>
        <td><%= player.first_name %></td>
        <td><%= player.last_name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_player_path(player), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      player_path(player),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='digg_pagination'>
  <%= will_paginate @players %>
</div>

<div class='form-actions'>

  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_player_path,
              :class => 'btn btn-primary' %>
</div>

app/views/players/new.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1>New Baseball Player Record</h1>
</div>
<%= render :partial => 'form' %>

app/views/players/show.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1>Baseball Player</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Player ID:</strong></dt>
  <dd><%= @player.player_id %></dd>

  <dt><strong>First Name:</strong></dt>
  <dd><%= @player.first_name %></dd>
  <dt><strong>Last Name:</strong></dt>
  <dd><%= @player.last_name %></dd>
  
  <dt><strong>Birth Year:</strong></dt>
  <dd><%= @player.birth_year %></dd>  
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              players_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_player_path(@player), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              player_path(@player),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>