config/routes.rb
Baseballstats::Application.routes.draw do

  # Search Routes
  get "search/index"
  post "search/improved"
  post "search/slugging"
  post "search/fantasy_improved"
  post "search/triple_crown"
  
  resources :players do
    collection { post :import }
  end

  resources :batting_statistics do
    collection { post :import }  
  end

  resources :fantasy_points

  root :to => 'home#index'  
end

app/models/batting_statistic.rb
########################################################################
# The BattingStatistic model is designed to hold the batting statistics
# for a single player for a given year. The statistics can either be
# imported or entered manually. The import format can be a CSV file with
# the following columns:
# 
# * playerID
# * yearID 
# * teamID
# * G - games played
# * AB - at batts
# * R - runs scored
# * H - hits
# * 2B - doubles
# * 3B - triples
# * HR - home runs
# * RBI - runs batted in 
# * SB - stolen bases
# * CS - caught stealing
#
# Each instance of the model object will also include calculated
# statistics for batting average and slugging percentage. These values
# will be calculated in callback methods. The entire set of batting
# statistics will be index by player_id.
########################################################################
class BattingStatistic
  include Mongoid::Document
  include Mongoid::Timestamps
  
  # Add call to strip leading and trailing white spaces from all atributes
  strip_attributes  # See strip_attributes for more information
  
  ## CALLBACKS ---------------------------------------------------------
  
  before_save :calc_batting_average
  before_save :calc_slugging_percent
  
  ## ATTRIBUTES --------------------------------------------------------
  
  field :player_id, type: String
  field :year, type: String
  field :team, type: String
  field :games_played, type: Integer, default: 0
  field :at_bats, type: Integer, default: 0
  field :runs_scored, type: Integer, default: 0
  field :hits, type: Integer, default: 0
  field :doubles, type: Integer, default: 0
  field :triples, type: Integer, default: 0
  field :home_runs, type: Integer, default: 0
  field :runs_batted_in, type: Integer, default: 0
  field :stolen_bases, type: Integer, default: 0
  field :caught_stealing, type: Integer, default: 0
  field :batting_average, type: Float, default: 0.0
  field :slugging_percent, type: Float, default: 0.0
  
  ## VALIDATIONS -------------------------------------------------------
  
  validates_presence_of :player_id
  validates_numericality_of :games_played, greater_than_or_equal_to: 0
  validates_numericality_of :at_bats, greater_than_or_equal_to: 0
  validates_numericality_of :runs_scored, greater_than_or_equal_to: 0
  validates_numericality_of :hits, greater_than_or_equal_to: 0
  validates_numericality_of :doubles, greater_than_or_equal_to: 0
  validates_numericality_of :triples, greater_than_or_equal_to: 0
  validates_numericality_of :home_runs, greater_than_or_equal_to: 0  
  validates_numericality_of :runs_batted_in, greater_than_or_equal_to: 0
  validates_numericality_of :stolen_bases, greater_than_or_equal_to: 0
  validates_numericality_of :caught_stealing, greater_than_or_equal_to: 0
  
  ## INDICES -----------------------------------------------------------
  
  index({player_id: 1}, {name: "player_index" })


  ## PREDEFINED SCOPES -------------------------------------------------

  scope :by_player, ->(player){ where(player_id: player).order_by([[:player_id, :asc]]) }
  
  # Returns results for a given year with min. at bats and sorted by player
  scope :by_year, ->(year, minbats){ where(year: year).gt(at_bats: minbats).order_by([[ :player_id, :asc ]])}
  
  # Returns results for a given year and team ordered by slugging percent
  scope :team_slugging, ->(year, team){ where(year: year, team: team).order_by([[ :slugging_percent, :desc ]])}

  ## PUBLIC CLASS METHODS ----------------------------------------------

  ######################################################################
  # Returns number of skipped rows during import.
  ######################################################################
  def self.skipped 
    return @@skipped_rows
  end  
  
  ######################################################################
  # The import method handles importing a CSV file of batting statistics.
  # It will overwrite the current set of statistics with the new ones
  # imported from the file.
  ######################################################################
  def self.import(file)
    BattingStatistic.delete_all
    @@skipped_rows = 0
    
    CSV.foreach(file.path, headers: true) do |row|
      if row['playerID'].present?
        stats = BattingStatistic.new
        stats.player_id = row['playerID']
        stats.year = row['yearID']
        stats.team = row['teamID']
        stats.games_played = row['G'] if !row['G'].nil?
        stats.at_bats = row['AB'] if !row['AB'].nil?
        stats.runs_scored = row['R'] if !row['R'].nil?
        stats.hits = row['H'] if !row['H'].nil?
        stats.doubles = row['2B'] if !row['2B'].nil?
        stats.triples = row['3B'] if !row['3B'].nil?
        stats.home_runs = row['HR'] if !row['HR'].nil?
        stats.runs_batted_in = row['RBI'] if !row['RBI'].nil?
        stats.stolen_bases = row['SB'] if !row['SB'].nil?
        stats.caught_stealing = row['CS'] if !row['CS'].nil?

        if !stats.save         
          logger.debug("[BattingStatistic.import] Could not save imported record - error: #{stats.errors.full_messages}")
        end
      else  
        @@skipped_rows += 1
      end
    end    
  end

  ## PRIVATE ITEMS -----------------------------------------------------
  
  private
    
  # Number of skipped rows during the import process
  @@skipped_rows = 0
    
  ######################################################################
  # The calc_batting_average will calculate the batting average and 
  # and store it in the model. This method is designed to be used
  # as a before_save callback.
  ######################################################################
  def calc_batting_average
    self.batting_average = hits / at_bats.to_f if at_bats > 0
  end

  ######################################################################
  # The calc_slugging_percent will calculate the slugging percentage and
  # store the value in the model object. This method is designed to be
  # used as a before_save callback.
  ######################################################################    
  def calc_slugging_percent
    self.slugging_percent = ((hits - doubles - triples - home_runs) + 
      (2 * doubles) + (3 * triples) + (4 * home_runs)) / at_bats.to_f if
      at_bats > 0 
  end
  
end

app/controllers/batting_statistics_controller.rb
########################################################################
# The BattingStatisticsController is responsible for managing the
# interaction and updating of BattingStatistic records. It has all the
# standard CRUD actions plus an action that supports uploading and
# replacing the system's batting statistics from a CSV file.
########################################################################
class BattingStatisticsController < ApplicationController

  ## CALLBACK DEFINITIONS ----------------------------------------------

  before_action :set_batting_statistic, only: [:show, :edit, :update, :destroy]
  before_action :set_batting_menu_active

  ######################################################################
  # GET /batting_statistics
  # GET /batting_statistics.json
  #
  # The index action method allows displaying all the currently loaded
  # batting statistics. It paginates them for easier access and shorter
  # load times. The view also includes an embedded form to enable
  # uploading of a new batting statistics file.
  ######################################################################
  def index
    # Get page number from paginate plugin used in view
    page = params[:page].nil? ? 1 : params[:page]
    
    @batting_statistics = BattingStatistic.order_by([[ :player_id, :asc ]]).paginate(
        page: page, per_page: PAGE_COUNT) # PAGE_COUNT is from parent
  end

  ######################################################################
  # GET /batting_statistics/1
  # GET /batting_statistics/1.json
  #
  # The show method displays an individual batting statistics record.
  # It also displays the caculated statistics of batting average and 
  # slugging percentage.
  ######################################################################
  def show
  end

  ######################################################################
  # GET /batting_statistics/new
  # 
  # Displays a new batting statistics form.
  ######################################################################
  def new
    @batting_statistic = BattingStatistic.new
  end

  ######################################################################
  # GET /batting_statistics/1/edit
  #
  # Displays an edit form for editing an existing batting statistics
  # record.
  ######################################################################
  def edit
  end

  ######################################################################
  # POST /batting_statistics
  # POST /batting_statistics.json
  #
  # Creates a new batting statistics record.  
  ######################################################################
  def create
    @batting_statistic = BattingStatistic.new(batting_statistic_params)

    respond_to do |format|
      if @batting_statistic.save
        format.html { redirect_to @batting_statistic, notice: 'Batting statistic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @batting_statistic }
      else
        format.html { render action: 'new' }
        format.json { render json: @batting_statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  ######################################################################
  # PATCH/PUT /batting_statistics/1
  # PATCH/PUT /batting_statistics/1.json
  #
  # Updates an existing batting statistics record.
  ######################################################################
  def update
    respond_to do |format|
      if @batting_statistic.update(batting_statistic_params)
        format.html { redirect_to @batting_statistic, notice: 'Batting statistic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @batting_statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  ######################################################################
  # DELETE /batting_statistics/1
  # DELETE /batting_statistics/1.json
  #
  # Destroys the requested batting statistics record
  ######################################################################
  def destroy
    @batting_statistic.destroy
    respond_to do |format|
      format.html { redirect_to batting_statistics_url }
      format.json { head :no_content }
    end
  end
  
  ######################################################################
  # POST /batting_statistics/import
  #
  # The import method allows uploading of a CSV file with batting 
  # statistics. It uses the BattingStatistic model import class method
  # for uploading the batting statistics.
  ######################################################################
  def import
    BattingStatistic.import(params[:file])
    message = "Battings statistics imported: #{BattingStatistic.count} successful and #{BattingStatistic.skipped} skipped."
    redirect_to batting_statistics_url, notice: message 
  end

  private
    ####################################################################
    # Use callbacks to share common setup or constraints between actions.
    ####################################################################
    def set_batting_statistic
      @batting_statistic = BattingStatistic.find(params[:id])
    end

    ####################################################################
    # Callback to set the Batting Stats menu to active state
    ####################################################################
    def set_batting_menu_active
      @batting_menu_active = 'class=active'    
    end

    ####################################################################
    # Never trust parameters from the scary internet, only allow the white list through.
    ####################################################################
    def batting_statistic_params
      params.require(:batting_statistic).permit(:player_id, :year, :team, :games_played, :at_bats, :runs_scored, :hits, :doubles, :triples, :home_runs, :runs_batted_in, :stolen_bases, :caught_stealing)
    end
end

app/helpers/batting_statistics_helper.rb
module BattingStatisticsHelper
end

app/views/batting_statistics/_form.html.erb
<%= form_for @batting_statistic, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :player_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :player_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :year, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :year, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :team, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :team, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :games_played, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :games_played, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :at_bats, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :at_bats, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :runs_scored, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :runs_scored, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :hits, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :hits, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :doubles, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :doubles, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :triples, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :triples, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :home_runs, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :home_runs, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :runs_batted_in, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :runs_batted_in, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :stolen_bases, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :stolen_bases, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :caught_stealing, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :caught_stealing, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                batting_statistics_path, :class => 'btn' %>
  </div>
<% end %>

app/views/batting_statistics/edit.html.erb
<%- model_class = BattingStatistic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/batting_statistics/index.html.erb
<%- model_class = BattingStatistic -%>
<div class="page-header">
  <h1>Batting Statistics</h1>  
  
  <div class="row-fluid">
    <div class="span8">
  
      <p>
        The list of batting statistics currently loaded in the system are
        shown in the table below. There are currently <strong>
        <%= BattingStatistic.count %></strong> batting statistic records
        loaded into the system.
      </p>
      <p>
        You can upload a new set of statistics into the system using the
        upload form below. <em>Please be aware that uploading a new
        set of statistics will replace the current set.</em>  All rows
        missing a <em>playerID</em> will be ignored. The file 
        format is expected to be in CSV format. The expected columns 
        and their order are shown to the right.
      </p>
      <br/>
      
      <!-- Upload form --------------------------------------------- -->
      <div class='pull-left' id="import">
        <%= form_tag import_batting_statistics_path, multipart: true do %>
          <%= file_field_tag :file %>
          <%= submit_tag "Import" %>
        <% end %>
      </div>  
    </div>
    
    <div class="well span3">
      <ol>
        <li>playerID</li>
        <li>yearID</li>
        <li>teamID</li>
        <li>G - games played</li>
        <li>AB - at batts</li>
        <li>R - runs scored</li>
        <li>H - hits</li>
        <li>2B - doubles</li>
        <li>3B - triples</li>
        <li>HR - home runs</li>
        <li>RBI - runs batted in</li>
        <li>SB - stolen bases</li>
        <li>CS - caught stealing</li>
      </ul>
    </div>
  </div>

</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Player ID</th>
      <th>Year</th>
      <th>Team</th>
      <th>Games Played</th>
      <th>At Bats</th>
      <th>Runs Scored</th>
      <th>Hits</th>
      <th>Doubles</th>
      <th>Triples</th>
      <th>Home Runs</th>
      <th>RBI</th>
      <th>Stolen Bases</th>
      <th>Caught Stealing</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @batting_statistics.each do |batting_statistic| %>
      <tr>
        <td><%= link_to batting_statistic.player_id, batting_statistic_path(batting_statistic) %></td>
        <td><%= batting_statistic.year %></td>
        <td><%= batting_statistic.team %></td>
        <td><%= batting_statistic.games_played %></td>
        <td><%= batting_statistic.at_bats %></td>
        <td><%= batting_statistic.runs_scored %></td>
        <td><%= batting_statistic.hits %></td>
        <td><%= batting_statistic.doubles %></td>
        <td><%= batting_statistic.triples %></td>
        <td><%= batting_statistic.home_runs %></td>
        <td><%= batting_statistic.runs_batted_in %></td>
        <td><%= batting_statistic.stolen_bases %></td>
        <td><%= batting_statistic.caught_stealing %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_batting_statistic_path(batting_statistic), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      batting_statistic_path(batting_statistic),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='digg_pagination'>
  <%= will_paginate @batting_statistics %>
</div>

<div class='form-actions'>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_batting_statistic_path,
            :class => 'btn btn-primary' %>
</div>

app/views/batting_statistics/new.html.erb
<%- model_class = BattingStatistic -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/batting_statistics/show.html.erb
<%- model_class = BattingStatistic -%>
<div class="page-header">
  <h1>Batting Statistics</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:player_id) %>:</strong></dt>
  <dd><%= @batting_statistic.player_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:year) %>:</strong></dt>
  <dd><%= @batting_statistic.year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:team) %>:</strong></dt>
  <dd><%= @batting_statistic.team %></dd>
  <dt><strong><%= model_class.human_attribute_name(:games_played) %>:</strong></dt>
  <dd><%= @batting_statistic.games_played %></dd>
  <dt><strong><%= model_class.human_attribute_name(:at_bats) %>:</strong></dt>
  <dd><%= @batting_statistic.at_bats %></dd>
  <dt><strong><%= model_class.human_attribute_name(:runs_scored) %>:</strong></dt>
  <dd><%= @batting_statistic.runs_scored %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hits) %>:</strong></dt>
  <dd><%= @batting_statistic.hits %></dd>
  <dt><strong><%= model_class.human_attribute_name(:doubles) %>:</strong></dt>
  <dd><%= @batting_statistic.doubles %></dd>
  <dt><strong><%= model_class.human_attribute_name(:triples) %>:</strong></dt>
  <dd><%= @batting_statistic.triples %></dd>
  <dt><strong><%= model_class.human_attribute_name(:home_runs) %>:</strong></dt>
  <dd><%= @batting_statistic.home_runs %></dd>
  <dt><strong><%= model_class.human_attribute_name(:runs_batted_in) %>:</strong></dt>
  <dd><%= @batting_statistic.runs_batted_in %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stolen_bases) %>:</strong></dt>
  <dd><%= @batting_statistic.stolen_bases %></dd>
  <dt><strong><%= model_class.human_attribute_name(:caught_stealing) %>:</strong></dt>
  <dd><%= @batting_statistic.caught_stealing %></dd>
  <dt><strong>Batting average:</strong></dt>
  <dd><%= @batting_statistic.batting_average.round(3) %></dd>
  <dt><strong>Slugging percentage:</strong></dt>
  <dd><%= @batting_statistic.slugging_percent.round(3) %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              batting_statistics_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_batting_statistic_path(@batting_statistic), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              batting_statistic_path(@batting_statistic),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>