config/routes.rb
Baseballstats::Application.routes.draw do

  # Search Routes
  get "search/index"
  post "search/improved"
  post "search/slugging"
  post "search/fantasy_improved"
  post "search/triple_crown"
  
  resources :players do
    collection { post :import }
  end

  resources :batting_statistics do
    collection { post :import }  
  end

  resources :fantasy_points

  root :to => 'home#index'  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Baseballstats" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'Baseball Stats', root_url, class: 'brand' %>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right">
              <li><%= link_to "Search", search_index_path  %></li>
              <li <%= @players_menu_active %>><%= link_to "Players", players_url %></li>
              <li <%= @batting_menu_active %>><%= link_to "Batting Stats", batting_statistics_url  %></li>              
              <li <%= @fantasy_menu_active %>><%= link_to "Fantasy", fantasy_points_url  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <!-- Image container -->
		<div class="container-fluid">
			<%= image_tag 'stadium_burns.jpg'%>
		</div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <br/>
          <%= render partial: 'shared/flash' %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p class='pull-right'>Demonstration Rails 4 Project<br/.>
        Photo credit - Flickr user Burns!</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>